name: Keep Backend Alive

on:
  schedule:
    # Run every 4 hours
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          curl -I https://adithyan321-caption-beast-backend.hf.space/
          echo "Ping sent to backend to prevent sleep."
